version: 0.1

phases:
  #install:
  #  commands:
  #    - pip install pyyaml
  build:
    commands:
      - echo Build started on `date`
      #- echo Compiling the Python code......
      - "zip lambda_function.zip lambda_function.py"
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - lambda_function.zip
  discard-paths: yes
  #base-directory: target