version: 0.2

phases:
  #install:
  #  commands:
  #    - pip install pyyaml
  build:
    commands:
      - echo Build started on `date`
      #- npm install
  post_build:
    commands:
      - echo Build completed on `date`
      #- mkdir build-output
      #- cp lambda_function.py build-output
      #- cd build-output/
      #- zip -qr build-output.zip ./*
      #- mv build-output.zip ../
      #- echo Build completed on `date`

artifacts:
  files:
    - lambda_function.py
  #discard-paths: yes
  #base-directory: target