version: 0.2

phases:
  #install:
  #  commands:
  #    - pip install pyyaml
  build:
    commands:
      - echo Build started on `date`
      #- echo Compiling the Python code......
      - "cd src && zip -r /target/lambda_function.zip ."
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - lambda_function.zip
  discard-paths: yes
  base-directory: target