version: 0.1

phases:
  #install:
  #  commands:
  #    - pip install pyyaml
  build:
    commands:
      - echo Build started on `date`
      #- echo Compiling the Python code......
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir build-output
      - cp lambda_function.py build-output
      - cd build-output/
      - zip -qr build-output.zip ./*
      - mv build-output.zip ../

artifacts:
  files:
    - build-output.zip
  #discard-paths: yes
  #base-directory: target