version: 0.2

phases:
  install:
    commands:
      – apt-get -y update
      – apt-get -y install zip
      - npm install -g serverless
  build:
    commands:
      - serverless deploy | tee deploy.out
  #post_build:
  #  commands:

#artifacts:
#  files:
#    - lambda_function.py
  #discard-paths: yes
  #base-directory: target
