version: 0.1

phases:
  #install:
  #  commands:
  #    - pip install pyyaml
  build:
    commands:
      - echo Build started on `date`
      #- echo Compiling the Python code......
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  type: zip
  files:
    - lambda_function.py
  #discard-paths: yes
  #base-directory: target